### ISSUE TITLE
Some logo ideas

### ISSUE THREAD

**Issue by jpwesselink** [workshopper/org#19]
I designed something quick snap. 

![w](https://cloud.githubusercontent.com/assets/1814479/19611118/737d6fb2-97e0-11e6-8373-70bebe56b2df.png)

**Comment by martinheidegger** [comment]
Very ["Wiener Werkstaette"](https://s-media-cache-ak0.pinimg.com/originals/70/a6/aa/70a6aa4541087188dbe0fd6b2d8f32bf.jpg) :)  

I like the first one the best, but the balance seems slightly off.

Also I wonder if it might be good to have

> WORKSHOPPER
> BUILD TO TEACH
> TEACH TO BUILD

in three paragraphs because workshopper is not written out in the logo.

**Comment by denysdovhan** [comment]
the first one +1
I like it.

**Comment by martinheidegger** [comment]
## QUOTING: @rynarud (from https://github.com/workshopper/workshopper/issues/130)

I've tried to figure out things:
![wshopper1](https://cloud.githubusercontent.com/assets/5675819/19623989/4b756eaa-98eb-11e6-9c73-041c05510bf9.png)
![wshopper2](https://cloud.githubusercontent.com/assets/5675819/19623991/5ca31d8a-98eb-11e6-8550-d211c97aa048.png)
![wshopper3](https://cloud.githubusercontent.com/assets/5675819/19623994/6eb62cba-98eb-11e6-8290-11f8eda5819f.png)
![wshopper4](https://cloud.githubusercontent.com/assets/5675819/19623995/7bcc46dc-98eb-11e6-9698-0cffef6fb303.png)

<hr>

Here I've used different colors to determine workshops. It's versatile to change.<br>
![wshopper5](https://cloud.githubusercontent.com/assets/5675819/19623998/83ab800c-98eb-11e6-9dfe-403d3df8fe7d.png)
![wshopper6](https://cloud.githubusercontent.com/assets/5675819/19624000/89b18d0c-98eb-11e6-93e8-ba36f4ff6dcc.png)
![wshopper7](https://cloud.githubusercontent.com/assets/5675819/19624001/910496b2-98eb-11e6-990d-4fd9dc3f3dd7.png)
![wshopper8](https://cloud.githubusercontent.com/assets/5675819/19624003/94f89a84-98eb-11e6-8bb3-dc229f4e1a6e.png)

<hr>

I'll be glad to get your feedback. Hope you like the general idea.

**Comment by ralphtheninja** [comment]
@rynarud Love it!

**Comment by martinheidegger** [comment]
@rynarud thank you for taking the time. A few things come to mind with the logo:
1. We  hex logos at Nodeschool and it would bengood it the logo would work as hex
2. If we have variants for each workshopper the I think that the name of the workshopper (I.e. learnyounode) should be bigger than the name workshopper
3. We might need to have single-color versions or with max two colors how would they look like?

**Comment by denysdovhan** [comment]
I've already commented https://github.com/workshopper/workshopper/issues/130#issuecomment-255584978.

Logos by @rynarud seem like **[oh-my-fish](https://github.com/oh-my-fish/oh-my-fish)** logo:

![image](https://cloud.githubusercontent.com/assets/3459374/19626120/8cfbe362-9932-11e6-8772-18056834826a.png)

**Comment by renmaiv** [comment]
@martinheidegger Thank you, it was a pleasure to work on it. However, I recommend updating the main post  https://github.com/workshopper/workshopper/issues/130 with the keypoints.
1. I mock up it quickly. As for me, it's looking a little bit weird, because of having already a hex in the logo.
   The option might be to rotate black hex or fit logo on it.
   ![hex](https://cloud.githubusercontent.com/assets/5675819/19629523/88ba9c88-997f-11e6-91cd-2650d153bb70.png)
2. It sounds reasonable. Here we have both heading and paragraph text. The logo is common for all workshops.  I note only the legibility issue with "LEARYOUNODE", through. <br>
   ![mdown](https://cloud.githubusercontent.com/assets/5675819/19631799/f289b01c-99a8-11e6-923d-51f90577be13.png)
3. The options: <br>
   ![mono](https://cloud.githubusercontent.com/assets/5675819/19629544/09d7c9b2-9980-11e6-8c20-00c4676e7e0e.png)

**Comment by renmaiv** [comment]
@denysdovhan Frankly speaking, I am not familiar with that framework (I haven't even recognized the fish in the logo while working on it 😃  ).

I've done research on Node.js communities and learning tools. Actually, it makes sense to be recognizable among them (but not all the tools).

Logos might be looking similar (style/form/color).  The core is an idea behind (">>" + "Node"). 

It seems to me, that ideas of OhMyFish and Workshopper are different.

**Comment by llkats** [comment]
Hi, I really love this. Both of them - @jpwesselink's minimalist take with the motto, and @rynarud's more graphic representation. I see the similarity in shape with oh-my-fish's logo, but that looks very much like a command prompt fish, and @rynarud's is more abstract. I think the difference in color/gradient, as well as the the carat overlapping more on the hexagon, help to differentiate the logos.

@rynarud, would it be possible to see a draft incorporating the motto "build to teach. teach to build."? Or what if JP's idea of using the letter W were used with (or instead of?) the hexagon, maybe something like `w»`? Maybe that would make it too complicated, not sure! Just trying to see how we could meld both ideas. Nice work all around!

**Comment by renmaiv** [comment]
@llkats Thank you for a great feedback. If I have enough time I'll reinvent it 👍

**Comment by martinheidegger** [comment]
Just some feedback:

> The option might be to rotate black hex or fit logo on it.

That is not really an option since hex logos kind-of stack that way, there is even a webpage dedicated to buy stickers shaped like this: https://hexi.pics/

**Comment by Flet** [comment]
also http://hexb.in/ :)

**Comment by denysdovhan** [comment]
Any updates?

**Comment by denysdovhan** [comment]
@workshopper/core hey, I don't see any updates here. I'm not happy with the fact that we still don't have nice logo:

![image](https://cloud.githubusercontent.com/assets/3459374/20815617/40c7c75e-b827-11e6-968b-5c8c8c1473ac.png)

We definitely should fix that. I propose to set the first one (or second, doesn't matter). That would look much more better _for now_.

And _we can easily change or improve our logo in future_.

What do you think?

**Comment by martinheidegger** [comment]
@rynarud 

> If I have enough time I'll reinvent it 👍

Do you think you have some time to reinvent it? The proposal does show promise.

**Comment by denysdovhan** [comment]
@workshopper/core so, what did we decide?

**Comment by martinheidegger** [comment]
In lieu of an answer from @rynarud I am for the first workshopper hexagon

**Comment by denysdovhan** [comment]
@martinheidegger me too.

**Comment by denysdovhan** [comment]
Also, even if we choose the logo from existing ones, I think it'd be better to leave this issue open.

**Comment by SomeoneWeird** [comment]
Agreed, we can always change, let's just get something to start with and roll with it

**Comment by martinheidegger** [comment]
@jpwesselink Do you have a vector version of Nr. 1?

**Comment by jpwesselink** [comment]
Definitely. SVG? EPS?

**Comment by martinheidegger** [comment]
Yes :) SVG i guess.

**Comment by jpwesselink** [comment]
I'll put minime in bed and then I'll convert that logo to svg

**Comment by jpwesselink** [comment]
Let me see if Santa has some gold coins to get some stickers made.

**Comment by denysdovhan** [comment]
@jpwesselink will be glad to see or even receive some stickers too :)

**Comment by jpwesselink** [comment]
I'll ask Santa :)

**Comment by jdorfman** [comment]
@jpwesselink Ho. Ho. Ho. Email me jdorfman @ stickermule.com

**Comment by jpwesselink** [comment]
@jdorfman didn't know Santa worked at Stickermule :)

**Comment by denysdovhan** [comment]
@jdorfman is this related only to @jdorfman? :))

**Comment by jdorfman** [comment]
@jpwesselink I started about 4 months ago giving out stickers to good open source deveopers. You and the rest of the workshopper team made the good list so, yeah.

OK can't do the Santa character anymore 😛. We would love to help out because that is my job. You can email me or we can do it publicly on GitHub e.g. https://github.com/gratipay/inside.gratipay.com/issues/137

**Comment by jpwesselink** [comment]
Dude we should sing a xmas carol for you : )

Let's do this publicly. What do you expect in return?

**Comment by jdorfman** [comment]
> Dude we should sing a xmas carol for you : )

I thought that went without saying. haha

> Let's do this publicly. 

Nice

> What do you expect in return?

Link back and/or Tweet thanking Santa Mule (@stickermule)

**Comment by martinheidegger** [comment]
I think the logo issue can be closed for now. @rynarud I would still love to see an updated version if you feel like contributing :heart:
