### ISSUE TITLE
Automated publishing

### ISSUE THREAD

**Issue by finnp** [workshopper/org#38]
I just updated a few things in `stream-adventure` and noticed that there is this whole process for deploying/publishing workshoppers.

I'm just wondering: How about simplifying this, by doing the npm publishes automatically from travis? This could be done e.g. by using [semantic-relase](https://github.com/semantic-release/semantic-release).

**Comment by martinheidegger** [comment]
Initially we thought it to be a good idea to have release guys in order to lower the effort on the people to understand semantic releases or that and to make it easier to contribute and in order to have more people looking over the code. I have not been following the progress of the projects but if this is an issue we can surely go the semeantic-release route. Please create a PR on [`./DEPLOYMENT.md`](https://github.com/workshopper/org/blob/master/DEPLOYMENT.md) to talk about specifics. Closing this Issue in anticipation of the PR
